apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightshift-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nightshift
  template:
    metadata:
      labels:
        app: nightshift
    spec:
      containers:
        - name: nightshift-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
            - containerPort: 8501