apiVersion: v1
kind: Service
metadata:
  name: nightshift-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nightshift
  ports:
    - name: game
      protocol: TCP
      port: {{ .Values.service.gamePort }}
      targetPort: 8000
    - name: dashboard
      protocol: TCP
      port: {{ .Values.service.dashboardPort }}
      targetPort: 8501