name: Integracion Continua (CI)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Construir la imagen de Docker
        working-directory: ./Backend
        run: docker build -t nightshift-app:latest .